DROP TABLE IF EXISTS medicine_prices;
DROP TABLE IF EXISTS medicines;
DROP TABLE IF EXISTS cities;

CREATE TABLE cities (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE medicines (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE medicine_prices (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id INT NOT NULL,
    medicine_id INT NOT NULL,
    price NUMERIC(10,2) NOT NULL CHECK (price > 0),
    price_date DATE NOT NULL DEFAULT CURRENT_DATE,
    FOREIGN KEY (city_id) REFERENCES cities(id),
    FOREIGN KEY (medicine_id) REFERENCES medicines(id),
    UNIQUE (city_id, medicine_id, price_date)
);

CREATE INDEX idx_city ON medicine_prices (city_id);
CREATE INDEX idx_medicine ON medicine_prices (medicine_id);
CREATE INDEX idx_date ON medicine_prices (price_date);
